//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespace) DeepCopyInto(out *BudgetNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespace.
func (in *BudgetNamespace) DeepCopy() *BudgetNamespace {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceCostBudgetSpec) DeepCopyInto(out *BudgetNamespaceCostBudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceCostBudgetSpec.
func (in *BudgetNamespaceCostBudgetSpec) DeepCopy() *BudgetNamespaceCostBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceCostBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceDefaultsSpec) DeepCopyInto(out *BudgetNamespaceDefaultsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceDefaultsSpec.
func (in *BudgetNamespaceDefaultsSpec) DeepCopy() *BudgetNamespaceDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceEnforcementSpec) DeepCopyInto(out *BudgetNamespaceEnforcementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceEnforcementSpec.
func (in *BudgetNamespaceEnforcementSpec) DeepCopy() *BudgetNamespaceEnforcementSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceEnforcementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceList) DeepCopyInto(out *BudgetNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BudgetNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceList.
func (in *BudgetNamespaceList) DeepCopy() *BudgetNamespaceList {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceQuotaSpec) DeepCopyInto(out *BudgetNamespaceQuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceQuotaSpec.
func (in *BudgetNamespaceQuotaSpec) DeepCopy() *BudgetNamespaceQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceSpec) DeepCopyInto(out *BudgetNamespaceSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Quota = in.Quota
	out.Defaults = in.Defaults
	out.Enforcement = in.Enforcement
	if in.CostBudget != nil {
		in, out := &in.CostBudget, &out.CostBudget
		*out = new(BudgetNamespaceCostBudgetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceSpec.
func (in *BudgetNamespaceSpec) DeepCopy() *BudgetNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetNamespaceStatus) DeepCopyInto(out *BudgetNamespaceStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastEnforcementAt != nil {
		in, out := &in.LastEnforcementAt, &out.LastEnforcementAt
		*out = (*in).DeepCopy()
	}
	if in.LastCostQueryAt != nil {
		in, out := &in.LastCostQueryAt, &out.LastCostQueryAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetNamespaceStatus.
func (in *BudgetNamespaceStatus) DeepCopy() *BudgetNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}
