name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache custom golangci-lint
        uses: actions/cache@v4
        with:
          path: |
            bin/golangci-lint-v2.13.0
            bin/golangci-lint-custom-v2.13.0
            ~/.cache/golangci-lint
          key: gci-${{ runner.os }}-v2.13.0-${{ hashFiles('.custom-gcl.yml', '.golangci.yml', 'go.sum') }}
          restore-keys: |
            gci-${{ runner.os }}-v2.13.0-

      - name: Download modules
        run: go mod download

      - name: Run linter
        run: make lint
